### ISSUE TITLE
vulkan / linux

### ISSUE THREAD

**Issue by slynobody** [artur-graniszewski/DLSS-Enabler#2] opened 2024-08-15 07:35 UTC
First of all thank you very much for your great work.

i tested beta 4 on linux with a vulkan-game, no mans sky. while it seemingly got gathered and plugged together all the necesarry stuff at startup, it stops while trying to open the vulkan-screen (winmm as well as version). did you change something in beta 5? if not is it necessary to change something inside the .ini to get it to work? i tried nearly all options regarding vulkan?

btw 1: do you have any idea how to get it to work in watch dogs 3? i tried beta 4, nothing.
btw 2: i am trying this on an amd polaris as well as on a steam-deck, is it possible in principle to plug together a frame-generation-only version? i have a few problems with ghosting-effects on the sd and just frame-generation seems to be a good compromise between image quality (no ghosting) and fps (fg)?

thank you for your help!

**Comment by artur-graniszewski** [comment] 2024-08-15 09:47
Hi,

Thanks for the feedback:)

You can find the game compatibility matrix here: https://docs.google.com/spreadsheets/d/1qsvM0uRW-RgAYsOVprDWK2sjCqHnd_1teYAx00_TwUY/edit?gid=1696395655#gid=1696395655

It is a bit incomplete as I struggle to find time to update it on time.

As for No Mans Sky: BETA 5 improves the compatibility with this game and Vulkan in general (confirmed working on GTX card under Windows), but its still something that will be marked as experimental during the public release of the newest version of the mod. We lack the necessary hardware to perform a broader test of that game under other GPUs and OSes, so it would be great if you could help us out by joining our Discord channel.


For now, due to the low level intricacies related to how dxvk works under Linux, by default. Vulkan support is disabled for that OS. I implemented an allow list with games for which DLSS Enabler reenables the support (for now: "No Man's Sky" and "Streamline Sample", while "Doom Ethernal" will be added in BETA 6). If you want to test other Vulkan games under Linux, find the "Vulkan" setting in nvngx.ini and set it from "auto" to "true".

As for Watchdogs 3 - you would have to send me the logs and/or perform a live troubleshooting session on Discord

When it comes to the last point - It depends on a game - most of them require DLSS upscaling to be on in order to unlock DLSSG (most of Unreal Engine games works like so). You can however use --dlss-upscaler-quality=ultra commandline argument, which will force DLSS Enabler to render everything in native resolution.

**Comment by slynobody** [comment] 2024-08-15 16:13
Thank you for your prompt help!
I tried Beta 5 with Vulkan in nvngx.ini set to true. It does not work again with version. Trying to start it with winmm it asked me to uninstall winmm first because of a version conflict? maybe a more recent version of winmm is needed (where would i get one)?

**Comment by artur-graniszewski** [comment] 2024-08-16 08:40
What winmm.dll file do you have installed already?

**Comment by slynobody** [comment] 2024-08-16 12:32
the one from the latest installer (beta5)

**Closed** 2024-09-30 11:48 UTC
